services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  # REDIS CONTAINER
  rd:
    image: redis:latest
    container_name: rd
    ports:
      - "6379:6379"

volumes:
  db_data: